# Generated by Django 5.0.6 on 2024-06-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='max_range',
            field=models.FloatField(),
        ),
    ]
